language: node_js
node_js:
  - lts/*
  - node

install:
  - npm ci
  - npm run link

script:
  - npm run lint
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run release
